In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('AREA_IMOVEL_1_MICRORREGIOESCSV.csv', encoding='cp1252')

In [3]:
df.head()

,FID,fid,the_geom,cod_tema,nom_tema,cod_imovel,mod_fiscal,num_area,ind_status,ind_tipo,des_condic,municipio,cod_estado,microrregiao
0,AREA_IMOVEL_1.2204921,2204921,MULTIPOLYGON (((258329.28170210187 7679431.775...,AREA_IMOVEL,Area do Imovel,ES-3203809-4B1D1EB212754AAF8B1DADD83286E134,0.24,7.28,AT,IRU,"Analisado, em conformidade com a Lei n 12.651/...",Muqui,ES,Central Sul
1,AREA_IMOVEL_1.2204922,2204922,MULTIPOLYGON (((248606.08848132257 7679481.293...,AREA_IMOVEL,Area do Imovel,ES-3203809-96BD394972004A06B3BBE0B93CE8F3F1,0.14,4.30,AT,IRU,"Analisado, em conformidade com a Lei n 12.651/...",Muqui,ES,Central Sul
2,AREA_IMOVEL_1.2204923,2204923,MULTIPOLYGON (((266820.27135844383 7680201.003...,AREA_IMOVEL,Area do Imovel,ES-3203809-907EE5221676490FAA97E23E35BF936B,0.34,10.10,AT,IRU,Aguardando analise,Muqui,ES,Central Sul
3,AREA_IMOVEL_1.2204924,2204924,MULTIPOLYGON (((258354.2801412465 7683293.6583...,AREA_IMOVEL,Area do Imovel,ES-3203809-F7FBE36F888D4EF39E0117D9A24AB3A7,0.03,1.00,PE,IRU,Aguardando analise,Muqui,ES,Central Sul
4,AREA_IMOVEL_1.2204925,2204925,MULTIPOLYGON (((260006.96317216655 7681789.581...,AREA_IMOVEL,Area do Imovel,ES-3203809-B6D11F2C90124B41A9FA8882E7742B97,0.25,7.52,AT,IRU,"Analisado, em conformidade com a Lei n 12.651/...",Muqui,ES,Central Sul

In [6]:
df['the_geom']

0         MULTIPOLYGON (((258329.28170210187 7679431.775...
1         MULTIPOLYGON (((248606.08848132257 7679481.293...
2         MULTIPOLYGON (((266820.27135844383 7680201.003...
3         MULTIPOLYGON (((258354.2801412465 7683293.6583...
4         MULTIPOLYGON (((260006.96317216655 7681789.581...
                                ...
124898    MULTIPOLYGON (((242031.65296004503 7736240.763...
124899    MULTIPOLYGON (((240828.24995876808 7737829.940...
124900    MULTIPOLYGON (((248780.84996669032 7730560.221...
124901    MULTIPOLYGON (((247488.70130914325 7679860.178...
124902    MULTIPOLYGON (((257714.16883120476 7685152.067...
Name: the_geom, Length: 124903, dtype: object

In [3]:
df_sample = df[['cod_imovel', 'municipio', 'microrregiao']]

In [4]:
microrregioes_lista = [
    'Central Sul', 
    'Noroeste', 
    'Centro-Oeste',
    'Nordeste',
    'Litoral Sul', 
    'Rio Doce', 
    'Central Serrana', 
    'Caparao',
    'Metropolitana', 
    'Sudoeste Serrana']

In [6]:
df_sample.head()

                                    cod_imovel municipio microrregiao
0  ES-3203809-4B1D1EB212754AAF8B1DADD83286E134     Muqui  Central Sul
1  ES-3203809-96BD394972004A06B3BBE0B93CE8F3F1     Muqui  Central Sul
2  ES-3203809-907EE5221676490FAA97E23E35BF936B     Muqui  Central Sul
3  ES-3203809-F7FBE36F888D4EF39E0117D9A24AB3A7     Muqui  Central Sul
4  ES-3203809-B6D11F2C90124B41A9FA8882E7742B97     Muqui  Central Sul

In [7]:
df_sample['cod_imovel'] = df_sample['cod_imovel'].map(lambda x: f"'{x}'")

/tmp/ipykernel_556/3621099784.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sample['cod_imovel'] = df_sample['cod_imovel'].map(lambda x: f"'{x}'")

In [8]:
df_sample.head()

                                      cod_imovel municipio microrregiao
0  'ES-3203809-4B1D1EB212754AAF8B1DADD83286E134'     Muqui  Central Sul
1  'ES-3203809-96BD394972004A06B3BBE0B93CE8F3F1'     Muqui  Central Sul
2  'ES-3203809-907EE5221676490FAA97E23E35BF936B'     Muqui  Central Sul
3  'ES-3203809-F7FBE36F888D4EF39E0117D9A24AB3A7'     Muqui  Central Sul
4  'ES-3203809-B6D11F2C90124B41A9FA8882E7742B97'     Muqui  Central Sul

In [11]:
df_aux = []

for locais in microrregioes_lista:
    # df_sample['cod_imovel'] = df_sample['cod_imovel'].map(lambda x: f"'{x}'")
    sample_1 = df_sample.loc[df_sample['microrregiao']==locais]['cod_imovel'].sample(n=1000, random_state=42)

    # sample_1['cod_imovel'] = sample_1['cod_imovel'].apply(lambda x: f"'{x}'")
    # linha_txt = ', '.join(sample_1)
    sample_1.to_csv(f'imoveis/{locais}.csv', index=False, sep=';')

    # sample_1 = sample_1.assign(microrregiao=locais)

    df_aux.append(sample_1)

df_final = pd.concat(df_aux, ignore_index=True)

df_final.to_csv('imoveis/amostra_total.csv', index=False, sep=';')


    # with open(f"{locais}.txt", 'w', encoding='utf-8') as f:
    #     f.write(linha_txt)

In [14]:
df_car = pd.read_csv("planilha_car.csv", sep=";")

In [15]:
df_car.head()

                                    cod_imovel              x             y
0  ES-3200102-F0415FE6E11042F6B9CD5AE4EA092116  275963.406933  7.782461e+06
1  ES-3200102-827B9D0C12B84F148D4E9DD0831334FC  281894.404795  7.758883e+06
2  ES-3200102-1E6857FEDADB486EB701CE71DE13CD94  265662.010413  7.776358e+06
3  ES-3200102-C1530B51750244568768A0648B308322  273187.828891  7.768422e+06
4  ES-3200102-9A5A14DFF21E44748A5003D63CA0BAC9  289401.171513  7.777017e+06

In [18]:
samples_car = df_car.merge(df_final, how="inner", on="cod_imovel")
samples_car.to_csv('imoveis/amostras_car.csv', sep=";", index=False)

In [1]:
with open('Caparao.txt', 'r') as f:
    # Junta tudo em uma string única caso seja uma linha só
    conteudo = f.read()
    # Separa pelo caractere de vírgula
    elementos = [e.strip().replace("'", "") for e in conteudo.split(',') if e.strip()]

In [6]:
elementos

['ES-3203007-CC452607BC104F43A3DB22261D9D0221',
 'ES-3203700-FA122914B46543FAA33E2038C95F5E7A',
 'ES-3203700-292EF64A361E4B088CEB060A5890D499',
 'ES-3202306-52CE6D39D2D24F289CC16122256A4726',
 'ES-3202454-E8D3A4CF9D88463FABD1B77D83C560C2',
 'ES-3204807-FB4EAC57000E4E86A42366BDB9FD55D4',
 'ES-3200201-AAB9AC623C83416598404BCBE523AD1E',
 'ES-3200201-864AA5160B5E422B98E57087E6DA1C37',
 'ES-3204807-8670EABEF0E840AF91D894633B2229B1',
 'ES-3202454-C2C4D8A9A7A8403098FFD6D2E5AA4F4C',
 'ES-3203700-10076A9BB8BC4E77B63F799535E15FC4',
 'ES-3201803-073A5B1F38D74469BCE406EB1AC786CF',
 'ES-3202306-AED958E8716842D293C97F8D4EA176B0',
 'ES-3203700-62F151F646134352A05C203D2F138147',
 'ES-3202454-75464C72E0F94AC6BA2988347CC251D4',
 'ES-3202009-3D8830A405C7420897C98AE67F91952F',
 'ES-3202454-AFC5E4E9870E4BF09E0C0F5BBBC90FA7',
 'ES-3202306-3054B099E2B74D79A80E190CFAE41E8A',
 'ES-3201803-B694C12F527E4365B460E03D20D7311E',
 'ES-3202553-9A097DE033074E01B3141FF482BA0028',
 'ES-3203007-C0BBB96B73AD412E80E7062C4219BBC0',
 'ES-3200201-6AC0BF32EECC40ED8DB8813A42E8F972',
 'ES-3204807-06AA11C629894E2F8DE6A43941167BB2',
 'ES-3202306-E15F14C1889746DF9034BB4D2BD32284',
 'ES-3203007-C7CFD8DB3B2E4A08BBEDD67893E3AE16',
 'ES-3202454-5C0F9143528C454CA257A92B76788724',
 'ES-3203007-ACC9C86EFBB14ED0BF4AEF247FEA67A7',
 'ES-3202009-D780E85140CC42BBA6B0221F77620277',
 'ES-3203700-4564B23EDC81481DA143BECDCA30114B',
 'ES-3202553-C5EF36FAA95D445E95AFA7BC9C735FAC',
 'ES-3202553-6C4D64537E354FE0B78C5552DDA11311',
 'ES-3202652-DA88752066C24E2E86BC09BE274AA749',
 'ES-3200201-4FCAB82680E0471FB256956274208C70',
 'ES-3202009-EEF42A02A7314FC0A79C0FD24D1D3E59',
 'ES-3204807-889EA9527B53458CBBFC9F534C2C25F6',
 'ES-3202652-92EA7BCDD15342968C5BB4032D8BECC8',
 'ES-3202009-44630B40795B4E658586380CFA9DA320',
 'ES-3202009-ECA1A7232CDF4E5480F6B4D56686AA83',
 'ES-3203007-5536132934FA4400AF7DEEF2D2CB24B8',
 'ES-3202306-197D0BB46E444E938B3999D78BC5CDEE',
 'ES-3200201-0E2995BB8A6E4060AA6BF34CB2EE676F',
 'ES-3203700-4527ADD2FCA6469087136ACEF77A8C62',
 'ES-3200201-A9664779F0F5424B8238A6F9A670223F',
 'ES-3203007-741BD198312646F8B6E0A595CC0E6474',
 'ES-3200201-4699D9F90DCD400E90FFC8DB04C1740D',
 'ES-3202652-5640F38885974420BAC2AAADA7C232C6',
 'ES-3200201-4ADA94A6059E4A4E982574AEE62F609B',
 'ES-3202652-50D65B117173447CB5F8F2EF4CAAE12C',
 'ES-3202652-2A2795B8B9FE4080AD7E6B80B81F7894',
 'ES-3203700-38F372E561AC467BB22A9DF7C3B5273B',
 'ES-3202306-2BE93C4AA3584F43BE517ED5C7C1FC7A',
 'ES-3202306-585B488710F6461EB1343B473A9FDA22',
 'ES-3201803-9B0E460E1F9B4100A19C9E18DF1F4D03',
 'ES-3200201-6019605123CD41659032D13B0B0D9ED1',
 'ES-3202553-7BB1EC7D793E4D0DADA7ED9FF72706E1',
 'ES-3200201-4DFD6C611CF8471384E2C18D05B82132',
 'ES-3202306-64ACEEF5D0DC41D0B0A3073ED149D637',
 'ES-3203007-8529F91AA7224CADB7BC0EC8C4B75908',
 'ES-3201803-1B850A14971242819B6E9B33BD9E8C70',
 'ES-3203700-03713ABDE0F64841A30202674AA89762',
 'ES-3201803-4EB246F91D14462AACC60E101C6310C8',
 'ES-3202652-61958AE578F64966B459E3EF650BAB40',
 'ES-3203700-C92D3B27A55C489F98DE5FFB7ADE4A3F',
 'ES-3200201-2709A485868449BBB1C515E50D7EFE9D',
 'ES-3202306-749A10FB2F244256B16CA4FD809E7F06',
 'ES-3202553-E47CB445D2C04885B973E862B3C0EA9E',
 'ES-3202652-ADEC94E033574C64B2E69F7051F2E229',
 'ES-3202009-CDFCA9EF32A048A091953DC398EAD93B',
 'ES-3203007-2022062F2C2C420EB4CC7897F5F489E8',
 'ES-3203700-8EDD1558A23149CABC619B3BB996FA04',
 'ES-3200201-6F0BC3558F1045059C83AED90F7FB48D',
 'ES-3204807-C21526B8DF4C438E9F5ADA6827133841',
 'ES-3203007-EEA179DFE8904BC68570409B799AF550',
 'ES-3202009-90A553CF03C249D4B226226F8D00E0DE',
 'ES-3202652-A6C6F5D67194461F99C4A6CCF93FF833',
 'ES-3202553-D69EDF5BBCAD4853AAADE204F29A2294',
 'ES-3202454-B695614E624449E2BE6C245C26910CC7',
 'ES-3202009-5B9FD49D848F41B28503982EBFED9B68',
 'ES-3202652-9505198BC00A4411859E24CE4B50E297',
 'ES-3203700-38AFB2F0A08D46518EDAD803461215DE',
 'ES-3203007-0C67BF159E124B12A8F5CB4CB4B3ECC5',
 'ES-3203007-905C8E90CF3D45219385B0DF3FCBDC68',
 'ES-3202652-C8D423AA93154BEEAA15513C3C4CAC8F',
 'ES-3202306-31969D4943E245DCB1F961516225A3A6',
 'ES-3200201-BB3B934A83EF47ED85E91ADC2AF530B7',
 'ES-3202009-B1773F09A48D41CCBBEBED93A3B6C479',
 'ES-3203700-D45FB90B780643F5AC2FCD9A9B04E121',
 'ES-3201803-FFDC3CCFC54549DD92DD710590E599DC',
 'ES-3200201-764F19BA5661449C83DC712F91A7F6CA',
 'ES-3202306-9DD02FE5E9FA411F9C7416D6F701FECC',
 'ES-3202553-97D9CE8C1860436D87D9416C7C9ACEB2',
 'ES-3200201-540C9EAC26C543919C34DBC3075F5C92',
 'ES-3203700-9A22179D193E417D8B7A7C2128AF36E6',
 'ES-3200201-AAF985B1F5EF4E5E851C413A00D7E307',
 'ES-3203007-15C6D856C8474349A336D42291000E54',
 'ES-3203007-CC1112B323A541DBBFB1B45F6A8A2B15',
 'ES-3202652-00DA139828E24D099968CBE1E6D41BBB',
 'ES-3204807-C0FBDE60EE4645F097BE1770DE8E1103',
 'ES-3201100-F2CA6D73771C47DF8FB3E6B08FEAF629',
 'ES-3203700-5EF38232CA164423BD5A66ED4358C92B',
 'ES-3202553-F589D59BC360428DA6E2472E229ED281',
 'ES-3200201-1A779AC21E1E41AF8756BFB81D2087B0',
 'ES-3200201-A4A6DCB3A460403FB2B85DD6E85DF6AC',
 'ES-3202652-A1CF294F085049F7AB77F26D6C40E4A4',
 'ES-3203700-EAE7A6D27F21431692EF52D95CC8EC15',
 'ES-3202306-FFFDC936DDA0406AA2E0BE625A219E92',
 'ES-3203007-3B6C6E5EB1CF4F7CAEF44B5E16384A95',
 'ES-3203007-AF00F59A24AF420B8D1CF813ACA37047',
 'ES-3203700-65FCC2EAE89548EE83B7418DB923241C',
 'ES-3202553-66AABCE382474E7CB02C6E188A14CC4C',
 'ES-3202454-730554AA660240AEBF81717854AC79E6',
 'ES-3202652-5AF916FE7E934B94ACC0F08B14091195',
 'ES-3202553-A73C621B1BB74D049DA7003D5E0CE64B',
 'ES-3203007-3D7B467B49C1485D93408C5F36BA9057',
 'ES-3200201-61C96B14EAAC48F28690F05075224185',
 'ES-3202454-FB378AD417664E308F6298F13F49CFB5',
 'ES-3203700-53E58487BCAE4C04B2E39CEC4EFBFF6E',
 'ES-3201803-35B94723358747E982F0BA3047C87F0F',
 'ES-3202553-BADCDC56F6884D10AACA253498AD78B5',
 'ES-3202009-DB59EB1934014B39B80340E12947CA38',
 'ES-3202553-1FFE33CAED184201853BE27C8E727FB6',
 'ES-3202306-1B36AA5AB75B48EDA707DD4617CA574A',
 'ES-3202553-D7E27D84A89B4EBB9C4E1ECB16707F79',
 'ES-3202454-4D20183462CE4CC8855CA039FCAD5E1F',
 'ES-3201100-A167BFBC6AFF4709BE15A685FBE876E8',
 'ES-3203700-E2EAC936C0A844D7B546A80F909E7A2A',
 'ES-3202553-FDEBFA23827743FB9D97E525605E6616',
 'ES-3202652-D2FA967E075B441DA222B9498FACE3D2',
 'ES-3202306-36695FC4CD3E4020B75E292552F6176F',
 'ES-3202652-E1ED128E72774A60A3E57DC78221FD1C',
 'ES-3200201-441AEC9862BF4EB0AD67BC691837F0DA',
 'ES-3203700-5A93AF6BE7F34C2FAD7F2E3C8DED6D70',
 'ES-3202009-D50B715AFD6B4E9EA37421C9F25DD41A',
 'ES-3202454-F95FAEA091A04AE3A1503C6B7BEC8609',
 'ES-3202454-00E6C86FBCD94C38B4D7989EE23AAA1C',
 'ES-3202306-B62A7EB31F28499FB0388B02F005AAC5',
 'ES-3203700-7B0FCF88A5F64AADB0305F80FE2B95BF',
 'ES-3201803-83A65EE056ED44E990CD7DBD430DAD1E',
 'ES-3202306-60F91A85345243ECA41CC4D1B7BD3E6B',
 'ES-3204807-7031CCF9EBD343E4B51AFE4275755161',
 'ES-3203007-D2267A0F3CC24179A2F9C1C8F02F259F',
 'ES-3202454-78DA359690D64C0294A605C200FEF262',
 'ES-3202454-A90C0ABEFCA649E2A46DA6674EEC917C',
 'ES-3204807-FF1AE4C3C5E64B4B8FA1FA8084246416',
 'ES-3202553-65C902D78E054223B0B0014D3C2F1BB0',
 'ES-3201803-BF23F22AEF3A494685239132B17E771C',
 'ES-3203700-52CE2BF1DBBF4B53A6C92A706EB3B92B',
 'ES-3203007-35F198B735CC448EA4CC47C7F2396BDA',
 'ES-3204807-38D568C4121F43AE8EDFA2E91888E2A9',
 'ES-3203007-342C1A2A76504F8FA0AC987F9BB2659D',
 'ES-3202306-29D1F3CDECFC4874A757EEB18B5B5AFE',
 'ES-3203700-750E47CC328C41B5A496DC09EEB51C87',
 'ES-3200201-D3C19D4C8EE04CFE843062A174C5EACA',
 'ES-3203700-2AEA31CA6707420593DC20E823F3AC54',
 'ES-3202306-6D9048DC177844FA80182ED95A12B887',
 'ES-3200201-41248F9E781E44C0AC91C95128C1C1AE',
 'ES-3202553-9468BF971C0E437ABF1869474901203F',
 'ES-3203700-AD58FF6F8CF144F29706898E83D67B3D',
 'ES-3202306-E62D1223CFAF483F89B04D8A2668C1FD',
 'ES-3202652-AF456D7C70E94AFC96BAE69681555BF4',
 'ES-3202652-CC4CF22ED5644A02BABE2F3D6C66D515',
 'ES-3202009-97A5B9AE74B54258912EEEDFB9714099',
 'ES-3200201-66FDC4D5B66A4495B7F2FF2C3147CED0',
 'ES-3201803-85BFF050D77C4EF2AA9223C418B5BC04',
 'ES-3202306-42F877E1E79A4DAA85EA9D9EB9EFD2B1',
 'ES-3203700-528C8F7F80FA46E98E961A71181CAA55',
 'ES-3200201-DD95ED241D7F476EBFB5D9F81B984272',
 'ES-3200201-A951782A7AAE45918353FF905B873DB9',
 'ES-3202009-17E202A1857C4769BE2C606248387BF4',
 'ES-3200201-434947DEDA4C43A99537B65E1507B741',
 'ES-3202454-B5F7641B89474D93938AB063867E3209',
 'ES-3203007-DB83DFB255B04CB886B5068585D54A22',
 'ES-3201100-5666873CAC3C4EB792A29F25D44CC97F',
 'ES-3202553-FE921D121B5C454B94A5B5540355AC1B',
 'ES-3202009-35390223E5B04F128077453FC1A06267',
 'ES-3202454-558096B0161245FD8565FCD99CE6FBEC',
 'ES-3201803-DD935BB029154DF5A1F753820F5E3D57',
 'ES-3203700-11C7B9EBE0474089A925C095A17028C3',
 'ES-3203007-1BCD85025780499D8B80FAFCD9ED0CF6',
 'ES-3202454-574257EA66414AEB90A760AE575C125F',
 'ES-3200201-41F1C870748C4BBBB471F02E9723EC2E',
 'ES-3203700-6812F788F1BA413C940C1AC29299CC82',
 'ES-3201803-11276DB6BDBD4DFA8C0FC12079F55BDA',
 'ES-3202652-85DB4C5DA4D446FB803AE43970B9F3CF',
 'ES-3204807-6F77ECEB77ED49D1BFB7562AD4B6929E',
 'ES-3202454-0AC3E77F993B45A488823D5C07F7DC98',
 'ES-3202454-C4BC8E974D5B466BAFCC912E24BA9873',
 'ES-3201100-50A1B6151B7B4855901956622320BDB9',
 'ES-3204807-3DB17619F49A423D87FC0B255AFB7F55',
 'ES-3203700-61775BA1934A4B149AF403814E08972F',
 'ES-3202553-9581DA58C3E540FA8E5261676A36E025',
 'ES-3203007-83F360920D8C4244A236A7795FDD3140',
 'ES-3202652-ECB324092EAF465C8627DDF53BB48C5B',
 'ES-3202009-84D8B0D92040436BB1B1C06874EF09E7',
 'ES-3202553-3932C4F3277C45C2845DE33B30844A44',
 'ES-3202652-E90FB4E24B2B42438AE0C3E35F763B39',
 'ES-3202306-D628D8654307494090395C200B352846',
 'ES-3203700-18767829A8C745119C054D608322D7B7',
 'ES-3202454-8EF1ABC246C94660B03767DC745DBD34',
 'ES-3202454-C350DAC597534E4185B7A0104293BDC5',
 'ES-3203700-8E3B619513DD4C968FBAE5EBEEF84F8A',
 'ES-3202009-E58B24FFBA9C41EFA32A17D3127FD75D',
 'ES-3203700-EBC34B9A2CEA48B4963435C54CC43DCD',
 'ES-3200201-4E64684D07C8460585CEBE54B6FF5CF7',
 'ES-3203007-1AFC7DB42B0E48E4A2456EC9F010C3FD',
 'ES-3200201-65E81120E5E74B54A30AD1EE42E26237',
 'ES-3202553-6546C405B35A41208E340F94D151F803',
 'ES-3204807-814817F9942B4D87ADE86ABF7C9A233E',
 'ES-3201803-9BCCE2A6A59041988063CEF4DF391513',
 'ES-3202454-95BD1C32F0474DD8A57A9840663F5F2B',
 'ES-3203007-87A1333734B4478AB3121F04EACD87F5',
 'ES-3200201-E2AC79F8242B45A9A65ACBB0376978D5',
 'ES-3203007-A524775D0890479B9091450A1CCE7111',
 'ES-3202652-03DFA46FF8474316BB71732B29375150',
 'ES-3202652-37777B92E4F94F6F92F6BB3F4570241D',
 'ES-3204807-81620AFFCFBC4033AD808486EBE7070A',
 'ES-3200201-42CF5698F07742DB9D74185EBA3E6637',
 'ES-3200201-492AE78EA8D2456FB3BBDC132DC11DA7',
 'ES-3202454-D2CE9FA7BF6A4CE99C39E8276F540D41',
 'ES-3203007-D556E80ABE634145A7EABD726FE86F80',
 'ES-3200201-B7640101E9694370968B286DB0F7605B',
 'ES-3202553-1B7972B9D7A843E996DBEB31056B9B73',
 'ES-3200201-D1117E2A58CF419BA2561F4019781278',
 'ES-3202009-3C525B01AE6E4C5B884D268A395624E4',
 'ES-3202306-4ECA83B091FC4A878273A1A4766E7BE6',
 'ES-3200201-6645265B773443D5A045DC99D7EA955F',
 'ES-3202652-E82ACD2BB6C941CDB06949486E2B3381',
 'ES-3200201-3D9E097A5AF84275A7EFAFE2ED45C56C',
 'ES-3202553-DAC3D0AE39FD4C31B423DC3E8DDE01C8',
 'ES-3201803-16E58E2BE9604F4BA36564F6A181A818',
 'ES-3200201-9E2E47D4A88D4EA0B5B3C97EC795CA6E',
 'ES-3200201-7B34F4A2AF8641CF9E5342DCF7E81E81',
 'ES-3201803-B5178264E05E44BE912D26A5C9BE259A',
 'ES-3202306-9652071542C14E1584D6191CDDFC6587',
 'ES-3203007-409BD87DEFE643EEAFA445DD096E4B2E',
 'ES-3202652-24BDCCF2D44D4EE1AD3014BC4C7E1604',
 'ES-3201803-A6FE5618C5ED4B408CBD0DF1881D3DE5',
 'ES-3202306-1BD40A0D32BA48379C19734D0DD53758',
 'ES-3202454-5A5065FB595540B49BE652036642542A',
 'ES-3202652-62035572B05C41289097919B9211B88B',
 'ES-3203700-37F5AF0D095845019267EA4C519F1B97',
 'ES-3202553-B6BF64AA5F4C40B4B7F5195EC2197A15',
 'ES-3203700-11269DD90A6D43BAA32F0588D1E5DE88',
 'ES-3202306-900C78DA168940ABB61B5AD295EC3AA8',
 'ES-3203700-C52842E2909B40A6BA88F6B1F2AE2AC2',
 'ES-3202454-70AE7BAB11874C54B1C1D7187E1AB123',
 'ES-3201803-F13D7336161F4809B3E16A23A6141512',
 'ES-3203007-9C7FE50AECC445579D450834A0829F21',
 'ES-3202306-7B92E8A84391482DA4BD8941137CEE61',
 'ES-3203700-52E909EEB4A842718317146FE0170A2B',
 'ES-3203007-C1F1F830E6E44B08B13C6B729DDC1D5E',
 'ES-3202652-D3A4381778D741BCAEBFF82BB3FE1648',
 'ES-3202306-7F7C8CC9EEEE40588AE2225FC1BE142A',
 'ES-3202652-554E90DCFF974A37882BE6260CD3FF26',
 'ES-3204807-095CAEF6FC3340DBA76E4A19066185EB',
 'ES-3203007-452E7153EABA43F69D4D6F854868DAB0',
 'ES-3202553-D2E11456566D4B22884CD496FB77B4FC',
 'ES-3203007-162D4AD6E9734CCA84979222D75859BB',
 'ES-3202652-142C1D55C32B4FD18C5B533E3FEC29EB',
 'ES-3200201-4CAEE14B2DF644F3BD9703F12697F35A',
 'ES-3202454-6FD84E79A6F44C239CFE56BAC9D484A1',
 'ES-3203700-B3E0C83D7C5B402A8C29A88B3E4D5EEC',
 'ES-3203007-54A4F580D1B14ECD9047B8BAA73230BA',
 'ES-3201803-5D86BC626793492A9A96ACF0D3820819',
 'ES-3201100-F918EA565C4D423598B62C189DCFFC83',
 'ES-3202306-F43F457A05E54724A03829447C7B573D',
 'ES-3200201-F7C321D1DBA9499EBC3AF9FC39D0BEB5',
 'ES-3202454-455B2CD4515046CA94C027346C7AA462',
 'ES-3202553-AA3FF545AB1342B9AF143F876AE0A4A9',
 'ES-3202652-5A8B8284E1844D82AAA01EDFDC28DB8C',
 'ES-3203007-F3FE5C7AC1D243A995E85962AA4D2212',
 'ES-3203700-B41C440781634872AE14D404A471E92E',
 'ES-3203007-6A8891F90B3D4FE3AF3C56BEC54079B8',
 'ES-3200201-01848C17153F4FF4BF850908E5275611',
 'ES-3200201-FDF99CD192824AA29C3C5205EC5529A3',
 'ES-3202454-695357AF7DE446848DDAC74FDADAC516',
 'ES-3202553-351DA080CDA6436E8E015BAED5BFFB27',
 'ES-3200201-837B9EEC47354763AEB475C359CBD063',
 'ES-3202454-48A8F2637B4B488F82CDD69CA82E8359',
 'ES-3203700-1EE0326AAC704723B1FD41EA27C600AC',
 'ES-3202454-2CB49CA825334CB0A4222A3208830DAF',
 'ES-3202553-35C3F7C64A424DB295BC1734EEFD5C17',
 'ES-3202652-323B3827AB154CDC8485B0138545554D',
 'ES-3202652-EC9D0A2FC04F411D803548860404E7CC',
 'ES-3202454-8E7F95DD4BAE4DF6BB0FC2F2FC9C5BB6',
 'ES-3201803-3AD100803D0445A48CB324BD4453D238',
 'ES-3202009-DDA6E5A2F4E4454CA9411BB81977F670',
 'ES-3203700-F9E3E8CCABEA4036BB4677B185379E79',
 'ES-3202652-1BBC11C38D4846EB89FD2494B47A8F10',
 'ES-3202454-84913C3947D747BB859D7767DFC5A25C',
 'ES-3200201-86967EDD16CD4DE7935C4A3F2CD48094',
 'ES-3202454-D328024896264AFD9F2091DAF52BB4B8',
 'ES-3201803-4C53202BD7FC4A4BB01E39AC51BB59B7',
 'ES-3202306-2E3AF2227FFD4F3BA334370C3FE89B2F',
 'ES-3202454-F3DFA72900144E41AB06BF9761E65921',
 'ES-3203700-1ED17B0768BD422AA55C7C9B9685CCF5',
 'ES-3202454-EFBAF5C3920442FFB94A246D070E7200',
 'ES-3200201-50459F031BDC4B5B8456DA2546A60F3F',
 'ES-3202306-D1F2A43338244BE8B2A97FA118DCDDC8',
 'ES-3203007-1C49A2C4BBEB4DC7B7ABAC57C5BBC728',
 'ES-3202454-7D015CDFD8464FFE981B89C9003D9B15',
 'ES-3200201-3EEB8A4CA74747F5A091CDCB9210CE07',
 'ES-3202652-220CDD7E5FB644108A7D5A014FF6C85C',
 'ES-3201803-A09D1966F32E4B36AF553EB5BE61CCEA',
 'ES-3202652-E85E73486FF646DE82DC813C11413502',
 'ES-3200201-192650B0E4444ADEA5271AB26A63125D',
 'ES-3202553-CED21E2710E244A591253C02F637F765',
 'ES-3202454-28C4F9D26E4C475BA4D6A12CEF2D108C',
 'ES-3200201-816239BEC34B4CEDAB0154ACFBCDD3ED',
 'ES-3200201-BA1BEC60ED5D47F194CFE1D0286969B8',
 'ES-3202454-B556CFFEFC0B4B889D719838C4C5A848',
 'ES-3203007-4F86FB5ED0364A24BC12042EC6DF08D2',
 'ES-3203700-3DDBD21B7BB94D89B52927A0E6158ECE',
 'ES-3202553-9D3DFA29AB164CEC80784F6EAD51483A',
 'ES-3202009-F56846A1E04047E5B2F6A5E8F6AE8A10',
 'ES-3203700-5A8EBD36A99A4FB9844E15A2E16906A7',
 'ES-3203007-5AF046BD281D41C99EA81594AB6DB356',
 'ES-3200201-691105E72610481985771308C582FB43',
 'ES-3202652-38E00F1470FD4A37A8316E1396589518',
 'ES-3200201-FF0DCE8EC02F40B69EF79DF13602790B',
 'ES-3202553-4E68FE92735245779CAA76C7F3A2CBD5',
 'ES-3200201-431F5B9CC15A481799AA0BD1D9C25F46',
 'ES-3202454-376D4D8A7ABC45C4AFD44C186F423AA9',
 'ES-3200201-87DD45FD1E5F4571A2BDE95EA4AF55AB',
 'ES-3200201-B05D51CE79E5432B98F66858ACDA0578',
 'ES-3202454-D3E5DE2A863343E3B726739AECEAB1B5',
 'ES-3202454-68A330B8B74A4F5E98D651C0FD34ABDB',
 'ES-3203700-1CBB4F9A5E4E414AA01DAD1F62CA5512',
 'ES-3203700-8FFA88C69272475CBB92E6222F892917',
 'ES-3203007-32FD1869D73A4A47B6604F3C6F54532E',
 'ES-3202306-720C78BEA1044313B2EEF056638576C3',
 'ES-3202652-0244507590E64986B2E1CBB33A436A02',
 'ES-3203700-2ED1496B85074DBCBC62F3BAFDE82B9D',
 'ES-3202454-F4664409FEC442D0955CD99831917565',
 'ES-3200201-CE9AF66474DD48AFBDEAE8D617553925',
 'ES-3202454-CBE704C785E34B6089E0CF1BF310349D',
 'ES-3200201-D612E69DBCD4482797ABBC3161E63D48',
 'ES-3203700-895ADA66DB4E4F27BDFD358FB4F78713',
 'ES-3203700-E3E850E524F94721B114D067CB9A0080',
 'ES-3202454-F339E5D4D5FF42FFB424FDDF9964209A',
 'ES-3203007-C5AB87E639A3433280C0CD4668CE5B8C',
 'ES-3200201-9BDE7FFE2A6D4B92968D26BABDCF973A',
 'ES-3202009-79B7DB9A27BB4B839E712B469B14413C',
 'ES-3203007-68AD67E4AB2741CE9625C655C64969D9',
 'ES-3202652-8380E5EAEE1041B4A2AA45EE0A89EC8A',
 'ES-3202009-FC867896D3F949EA874DB0395D60FCD2',
 'ES-3202652-1AF78E2BDEE3455681753A36EEE7AFBC',
 'ES-3201803-EEA3081A83EC4C4B9E97268D7A1A3379',
 'ES-3203007-7CCCB15164E24996A61F6E657F4DC75F',
 'ES-3203007-3CB0E7FF4D2C45C8BF8DBE88833A5F6D',
 'ES-3203700-BEEF091B0F374C38925645B8B01A8010',
 'ES-3203700-7AA27647EAE942B2B6F60AC03659C292',
 'ES-3202454-026934429B554D23892DF10B536A2383',
 'ES-3202652-3A261775332F474191E11E7A0FD6647B',
 'ES-3201803-03D9659E116D4028BCB39455AFE7AECF',
 'ES-3201803-32A721B872DC4F748E761896AA61F36F',
 'ES-3203403-B24354A1B5FC42B38DB988EA8B6D620F',
 'ES-3203700-AAF47FE799AB4BF9B321BCD3BE1EFC9B',
 'ES-3203007-DDAA7EB0D9364BB19EB94CE59AC78CB0',
 'ES-3202652-C0DF8433818A4B2AA557FDEE031E4503',
 'ES-3202009-D8417A3813A74BBFB88E19A9DD70FA9C',
 'ES-3200201-E24A5D2A67DC478AAF46393D2B3DB5EB',
 'ES-3203007-47F93FE10C2744469B0A91DC6C3407D0',
 'ES-3202652-A50335875C9D48E592D3411A1DAEBAFF',
 'ES-3202454-C74E67C95F884C249DE74602CD530996',
 'ES-3202652-0EAB7515FED9401BAFE78D01DA304DCE',
 'ES-3203700-B114E89152D74EE18DD278C3C484CE64',
 'ES-3204807-74A38AF20BC6441E989791286F3E4872',
 'ES-3202652-2CACB7A8A8F04BD5A6C9497F544E2A15',
 'ES-3200201-E217C78157E247B999685652411F0828',
 'ES-3203007-ABE8DF1693F746B29F2BEA12CCC7CD89',
 'ES-3202553-3EAB42B8200A4297B14381C8B47BA409',
 'ES-3203700-EE39042AF10C4605B05F3E7E44AC0381',
 'ES-3200201-C1280131A0D049BEA94E3A4CF99A9A7A',
 'ES-3201803-52AEBDA6E361430BB3B9E3572ACB63C5',
 'ES-3201803-168FFDEAA1924BD48D6396ACE6CF32C2',
 'ES-3202553-CACB02A31212426EB9AE254D15A2281A',
 'ES-3202306-3538F038DB454D319165F5CC9F35B354',
 'ES-3203007-5323E31816494686A507E22E17ACF8E0',
 'ES-3203700-2F3C644003294C2A9DC72753CE25A7A4',
 'ES-3203700-1862170F1E3745DB9578D00A14A5675B',
 'ES-3202454-D69FEC8013D04C7F8887326E226C9E21',
 'ES-3202553-FCA9F88E4B9241249E0ED24827985548',
 'ES-3202652-8A884F3C583A47E09B2FD810931982B7',
 'ES-3202009-1097AAFBA708481890CE7FE563E9B35E',
 'ES-3202454-567D7039663F4744AFC16917D673EED6',
 'ES-3202553-56E276721ADC464385C88F53706CB272',
 'ES-3202454-3EF3EFB5E7B9482DA41A71A782AC39FA',
 'ES-3200201-F11971F176C24400B6703DBFB22DE82C',
 'ES-3202652-66CBF67923C9434A95D6DBBA449A5C0B',
 'ES-3200201-BB9C84973D094165AAC571FDD2E23AA6',
 'ES-3200201-B681B050CD68409FBC641F65B1EA60CB',
 'ES-3200201-E9DAE65EEAB64A56988961A798E92E55',
 'ES-3202454-913D317C7BC9486CB68148B876D4600D',
 'ES-3202553-0792C2B2C67C46EBBAA2CA4CC84CBE2B',
 'ES-3203700-3D506C8817C64F79A9100876C5A7F5F5',
 'ES-3200201-0F6E7BBFDF31461CA795CD8D7481833F',
 'ES-3203700-928B116FAF504556B182B33D8521257B',
 'ES-3203007-30A4D170F2EC4486A4FC382178C25FBC',
 'ES-3203700-D6DFB3ECBF41479BAFD5A94E6BF6DA69',
 'ES-3204807-13694248E1EA4A88A25CB73A263437D0',
 'ES-3202454-902357AF872B4FDC9C314714DD2FB5D6',
 'ES-3202454-D20C62354D3C441F8DE331356091AACB',
 'ES-3202652-D3CE7E0C7DC449F8A871C364C989E454',
 'ES-3201803-69D77D32B3E347709B6F31E01DF9535A',
 'ES-3201803-DF05CD39C0D94334BCD7A60E81DEDDD4',
 'ES-3203007-C8C8715027D94B56BCC4F5FF4F191C94',
 'ES-3200201-F1A97CD95CA447BB82BF12CEC904EBD2',
 'ES-3202553-B0318DDB7E1D4FCEA0ABCEE73D85D373',
 'ES-3203007-CF001C14DD5E4C6FBF3B6BABDCF09F89',
 'ES-3203700-1DCF96DCE77C4A71963829628A1E9E57',
 'ES-3200201-DFB7F6CBAF984CB4BAB2B2C0EB1030CA',
 'ES-3202553-EAF7BBFCF983473F9B3C4DB9F7268060',
 'ES-3201100-BBC9EE7603B143EAB1054C63855634A9',
 'ES-3202454-7DB1698BD5B54543934A95CDF000DC47',
 'ES-3200201-89D84DCA213A47469CD4A2CFA0DCBF67',

In [10]:
with open('/home/calebe/Área de trabalho/car_images_dowload/Caparao.txt', 'r') as f:
    conteudo = f.read()
    elementos = [e.strip().replace("'", "") for e in conteudo.split(',') if e.strip()]
print(f"Exemplo de elementos: {elementos[:5]}")  # Veja os primeiros IDs

Exemplo de elementos: ['ES-3203007-CC452607BC104F43A3DB22261D9D0221', 'ES-3203700-FA122914B46543FAA33E2038C95F5E7A', 'ES-3203700-292EF64A361E4B088CEB060A5890D499', 'ES-3202306-52CE6D39D2D24F289CC16122256A4726', 'ES-3202454-E8D3A4CF9D88463FABD1B77D83C560C2']

In [11]:
for f in camada_pontos.getFeatures():
    print(f['cod_imovel'])
    # Opcional: break depois de alguns (exemplo, 20) para não inundar o terminal
    # break

NameError: name 'camada_pontos' is not defined